// data.js - Toutes les données de l'application (VERSION ENRICHIE)

// ========================================
// 80+ QUESTIONS POUR LE QUIZ
// ========================================
const allQuestions = [
    {q: 'Comment dit-on "Bonjour" ?', o: ['Bonswa', 'Bonjou', 'Salut', 'Orevwa'], c: 1},
    {q: 'Que signifie "Sa ou fè" ?', o: ['Où vas-tu', 'Comment ça va', 'Qui es-tu', 'Que fais-tu'], c: 1},
    {q: 'Particule du présent ?', o: ['té', 'kay', 'ka', 'pa'], c: 2},
    {q: 'Comment dit-on "Merci beaucoup" ?', o: ['Mèsi', 'Mèsi anlo', 'Souplé', 'Pa ni pwoblèm'], c: 1},
    {q: 'Que signifie "Man ka chèché" ?', o: ['Je cherche', 'Je mange', 'Je dors', 'Je parle'], c: 0},
    {q: 'Particule du passé ?', o: ['ka', 'té', 'kay', 'pa'], c: 1},
    {q: 'Comment dit-on "les enfants" ?', o: ['timoun', 'timoun-la', 'sé timoun', 'timoun-yo'], c: 2},
    {q: 'Que signifie "I bon" ?', o: ['Il est grand', 'C\'est bon', 'Il vient', 'C\'est cher'], c: 1},
    {q: 'Comment dit-on "Au revoir" ?', o: ['Bonjou', 'Mèsi', 'Orevwa', 'Souplé'], c: 2},
    {q: 'Que signifie "Mwen fen" ?', o: ['J\'ai faim', 'J\'ai soif', 'Je pars', 'Je viens'], c: 0},
    {q: 'Particule du futur ?', o: ['ka', 'té', 'kay', 'pa'], c: 2},
    {q: 'Comment dit-on "Oui" ?', o: ['Wi', 'Non', 'Pa', 'Wa'], c: 0},
    {q: 'Que signifie "Koté ou ka alé" ?', o: ['Qui es-tu', 'Où vas-tu', 'Comment vas-tu', 'Que fais-tu'], c: 1},
    {q: 'Comment dit-on "S\'il te plaît" ?', o: ['Mèsi', 'Souplé', 'Padon', 'Orevwa'], c: 1},
    {q: 'Que signifie "Konben sa kouté" ?', o: ['Qui est-ce', 'Où est-ce', 'C\'est combien', 'Comment'], c: 2},
    {q: 'Le pluriel se marque avec :', o: ['yo', 'la', 'sé', 'ka'], c: 2},
    {q: 'Comment dit-on "Je t\'aime" ?', o: ['Mwen enmen\'w', 'Mwen fen', 'Mwen bien', 'Mwen ka alé'], c: 0},
    {q: 'Où se place l\'adjectif généralement ?', o: ['Avant le nom', 'Après le nom', 'Les deux', 'Aucun'], c: 1},
    {q: 'Que signifie "An nou alé" ?', o: ['Allons-y', 'Au revoir', 'Bonjour', 'Merci'], c: 0},
    {q: 'Comment dit-on "Excuse-moi" ?', o: ['Mèsi', 'Padon', 'Eskizé mwen', 'Souplé'], c: 2},
    {q: 'Que signifie "Mwen swef" ?', o: ['J\'ai faim', 'J\'ai soif', 'Je suis fatigué', 'Je pars'], c: 1},
    {q: 'Comment dit-on "Maison" ?', o: ['Kay', 'Fanm', 'Nonm', 'Timoun'], c: 0},
    {q: 'Que signifie "Fanm" ?', o: ['Homme', 'Femme', 'Enfant', 'Maison'], c: 1},
    {q: 'Comment dit-on "Homme" ?', o: ['Fanm', 'Nonm', 'Timoun', 'Kay'], c: 1},
    {q: 'Que signifie "Ba mwen" ?', o: ['Donne-moi', 'Prends', 'Va', 'Viens'], c: 0},
    {q: 'Comment dit-on "Eau" ?', o: ['Dlo', 'Pen', 'Diri', 'Manjé'], c: 0},
    {q: 'Que signifie "Manjé" ?', o: ['Boire', 'Manger', 'Dormir', 'Parler'], c: 1},
    {q: 'Comment dit-on "Pain" ?', o: ['Dlo', 'Pen', 'Diri', 'Vyann'], c: 1},
    {q: 'Que signifie "Diri" ?', o: ['Riz', 'Pain', 'Eau', 'Viande'], c: 0},
    {q: 'Comment dit-on "Grand" ?', o: ['Ti', 'Gwo', 'Bèl', 'Vyé'], c: 1},
    {q: 'Que signifie "Ti" ?', o: ['Grand', 'Petit', 'Beau', 'Vieux'], c: 1},
    {q: 'Comment dit-on "Beau/Belle" ?', o: ['Bèl', 'Lèd', 'Gwo', 'Ti'], c: 0},
    {q: 'Que signifie "Vyé" ?', o: ['Jeune', 'Vieux', 'Nouveau', 'Ancien'], c: 1},
    {q: 'Comment dit-on "Nouveau" ?', o: ['Vyé', 'Nèf', 'Jenn', 'Gran'], c: 1},
    {q: 'Que signifie "Jenn" ?', o: ['Vieux', 'Jeune', 'Grand', 'Petit'], c: 1},
    {q: 'Comment dit-on "Nuit" ?', o: ['Jou', 'Nwit', 'Maten', 'Aswè'], c: 1},
    {q: 'Que signifie "Jou" ?', o: ['Nuit', 'Jour', 'Matin', 'Soir'], c: 1},
    {q: 'Comment dit-on "Matin" ?', o: ['Nwit', 'Aswè', 'Maten', 'Midi'], c: 2},
    {q: 'Que signifie "Aswè" ?', o: ['Matin', 'Midi', 'Soir', 'Nuit'], c: 2},
    {q: 'Comment dit-on "Aujourd\'hui" ?', o: ['Yè', 'Jòdi', 'Dèmen', 'Lontan'], c: 1},
    {q: 'Que signifie "Dèmen" ?', o: ['Hier', 'Aujourd\'hui', 'Demain', 'Maintenant'], c: 2},
    {q: 'Comment dit-on "Hier" ?', o: ['Jòdi', 'Dèmen', 'Yè', 'Lontan'], c: 2},
    {q: 'Que signifie "Lontan" ?', o: ['Bientôt', 'Longtemps', 'Maintenant', 'Jamais'], c: 1},
    {q: 'Comment dit-on "Maintenant" ?', o: ['Lontan', 'Kounnyé-a', 'Aprézan', 'Dèmen'], c: 1},
    {q: 'Que signifie "Vini" ?', o: ['Aller', 'Venir', 'Partir', 'Rester'], c: 1},
    {q: 'Comment dit-on "Aller" ?', o: ['Vini', 'Alé', 'Rété', 'Pati'], c: 1},
    {q: 'Que signifie "Rété" ?', o: ['Partir', 'Venir', 'Rester', 'Aller'], c: 2},
    {q: 'Comment dit-on "Partir" ?', o: ['Vini', 'Alé', 'Rété', 'Pati'], c: 3},
    {q: 'Que signifie "Palé" ?', o: ['Écouter', 'Parler', 'Voir', 'Entendre'], c: 1},
    {q: 'Comment dit-on "Écouter" ?', o: ['Palé', 'Tann', 'Wè', 'Konprann'], c: 1},
    {q: 'Que signifie "Wè" ?', o: ['Entendre', 'Voir', 'Parler', 'Comprendre'], c: 1},
    {q: 'Comment dit-on "Comprendre" ?', o: ['Palé', 'Tann', 'Wè', 'Konprann'], c: 3},
    {q: 'Que signifie "Sav" ?', o: ['Savoir', 'Pouvoir', 'Vouloir', 'Devoir'], c: 0},
    {q: 'Comment dit-on "Pouvoir" ?', o: ['Sav', 'Pé', 'Lé', 'Dwèt'], c: 1},
    {q: 'Que signifie "Lé" ?', o: ['Savoir', 'Pouvoir', 'Vouloir', 'Devoir'], c: 2},
    {q: 'Comment dit-on "Devoir" ?', o: ['Sav', 'Pé', 'Lé', 'Dwèt'], c: 3},
    {q: 'Que signifie "Bwè" ?', o: ['Manger', 'Boire', 'Dormir', 'Chanter'], c: 1},
    {q: 'Comment dit-on "Dormir" ?', o: ['Bwè', 'Dòmi', 'Manjé', 'Chanté'], c: 1},
    {q: 'Que signifie "Chanté" ?', o: ['Danser', 'Chanter', 'Jouer', 'Rire'], c: 1},
    {q: 'Comment dit-on "Danser" ?', o: ['Chanté', 'Dansé', 'Jwé', 'Ri'], c: 1},
    {q: 'Que signifie "Jwé" ?', o: ['Travailler', 'Jouer', 'Étudier', 'Dormir'], c: 1},
    {q: 'Comment dit-on "Travailler" ?', o: ['Jwé', 'Travay', 'Étidyé', 'Dòmi'], c: 1},
    {q: 'Que signifie "Kouri" ?', o: ['Marcher', 'Courir', 'Sauter', 'Voler'], c: 1},
    {q: 'Comment dit-on "Marcher" ?', o: ['Kouri', 'Maché', 'Soté', 'Volé'], c: 1},
    {q: 'Que signifie "Gadé" ?', o: ['Regarder', 'Écouter', 'Toucher', 'Sentir'], c: 0},
    {q: 'Comment dit-on "Chercher" ?', o: ['Gadé', 'Chèché', 'Jwenn', 'Pwan'], c: 1},
    {q: 'Que signifie "Jwenn" ?', o: ['Chercher', 'Trouver', 'Perdre', 'Donner'], c: 1},
    {q: 'Comment dit-on "Prendre" ?', o: ['Donné', 'Pwan', 'Jwenn', 'Chèché'], c: 1},
    {q: 'Que signifie "Bay" ?', o: ['Prendre', 'Donner', 'Garder', 'Perdre'], c: 1},
    {q: 'Comment dit-on "Garder" ?', o: ['Bay', 'Pwan', 'Gadé', 'Kité'], c: 2},
    {q: 'Que signifie "Kité" ?', o: ['Garder', 'Prendre', 'Laisser', 'Donner'], c: 2},
    {q: 'Comment dit-on "Aimer" ?', o: ['Rayi', 'Enmen', 'Vwè', 'Konnen'], c: 1},
    {q: 'Que signifie "Rayi" ?', o: ['Aimer', 'Détester', 'Vouloir', 'Savoir'], c: 1},
    {q: 'Comment dit-on "Chaud" ?', o: ['Frèt', 'Cho', 'Tyèd', 'Glase'], c: 1},
    {q: 'Que signifie "Frèt" ?', o: ['Chaud', 'Froid', 'Tiède', 'Glacé'], c: 1},
    {q: 'Comment dit-on "Rouge" ?', o: ['Vè', 'Ble', 'Rouj', 'Jòn'], c: 2},
    {q: 'Que signifie "Vè" ?', o: ['Rouge', 'Bleu', 'Vert', 'Jaune'], c: 2},
    {q: 'Comment dit-on "Bleu" ?', o: ['Vè', 'Ble', 'Rouj', 'Blan'], c: 1},
    {q: 'Que signifie "Blan" ?', o: ['Noir', 'Blanc', 'Gris', 'Brun'], c: 1},
    {q: 'Comment dit-on "Noir" ?', o: ['Blan', 'Nwè', 'Gri', 'Bren'], c: 1}
];

// ========================================
// 80+ EXPRESSIONS COURANTES (ENRICHIES)
// ========================================
const expressions = [
    { fr: 'Bonjour', cr: 'Bonjou' },
    { fr: 'Bonsoir', cr: 'Bonswa' },
    { fr: 'Bonne nuit', cr: 'Bon nwit' },
    { fr: 'Comment ça va ?', cr: 'Sa ou fè ?' },
    { fr: 'Ça va bien', cr: 'Sa ka maché' },
    { fr: 'Très bien merci', cr: 'Bien mèsi' },
    { fr: 'Merci', cr: 'Mèsi' },
    { fr: 'Merci beaucoup', cr: 'Mèsi anlo' },
    { fr: 'De rien', cr: 'Pa ni pwoblèm' },
    { fr: 'S\'il te plaît', cr: 'Souplé' },
    { fr: 'S\'il vous plaît', cr: 'Souplé' },
    { fr: 'Excuse-moi', cr: 'Eskizé mwen' },
    { fr: 'Pardon', cr: 'Padon' },
    { fr: 'Au revoir', cr: 'Orevwa' },
    { fr: 'À bientôt', cr: 'A ta lè' },
    { fr: 'À plus tard', cr: 'A pli ta' },
    { fr: 'À tout à l\'heure', cr: 'A talè' },
    { fr: 'Oui', cr: 'Wi' },
    { fr: 'Non', cr: 'Non' },
    { fr: 'D\'accord', cr: 'Dakò' },
    { fr: 'Je ne sais pas', cr: 'Man pa sav' },
    { fr: 'Je ne comprends pas', cr: 'Man pa konprann' },
    { fr: 'Comment tu t\'appelles ?', cr: 'Ki jan ou rélé ?' },
    { fr: 'Je m\'appelle...', cr: 'Man rélé...' },
    { fr: 'Enchanté', cr: 'Anchonté' },
    { fr: 'Où vas-tu ?', cr: 'Koté ou ka alé ?' },
    { fr: 'Je vais bien', cr: 'Man bien' },
    { fr: 'J\'ai faim', cr: 'Mwen fen' },
    { fr: 'J\'ai soif', cr: 'Mwen swef' },
    { fr: 'J\'ai sommeil', cr: 'Mwen ni dòmi' },
    { fr: 'Je suis fatigué', cr: 'Man las' },
    { fr: 'C\'est délicieux', cr: 'I bon anlo' },
    { fr: 'C\'est bon', cr: 'I bon' },
    { fr: 'C\'est mauvais', cr: 'I pa bon' },
    { fr: 'Combien ça coûte ?', cr: 'Konben sa kouté ?' },
    { fr: 'C\'est cher', cr: 'Sa chè' },
    { fr: 'C\'est pas cher', cr: 'Sa pa chè' },
    { fr: 'Je cherche...', cr: 'Man ka chèché...' },
    { fr: 'Je voudrais...', cr: 'Man té lé...' },
    { fr: 'Allons-y !', cr: 'An nou alé !' },
    { fr: 'Attends', cr: 'Tann' },
    { fr: 'Attends-moi', cr: 'Tann mwen' },
    { fr: 'Dépêche-toi', cr: 'Fè vit' },
    { fr: 'Pas de problème', cr: 'Pa ni pwoblèm' },
    { fr: 'Aucun souci', cr: 'Pon pwoblèm' },
    { fr: 'Je t\'aime', cr: 'Mwen enmen\'w' },
    { fr: 'Je t\'adore', cr: 'Mwen adò\'w' },
    { fr: 'Mon amour', cr: 'Doudou mwen' },
    { fr: 'Mon chéri / Ma chérie', cr: 'Chè mwen' },
    { fr: 'Ma belle / Mon beau', cr: 'Bèl mwen' },
    { fr: 'Quel est ton nom ?', cr: 'Ki non\'w ?' },
    { fr: 'D\'où viens-tu ?', cr: 'Koté ou sòti ?' },
    { fr: 'Je viens de France', cr: 'Mwen sòti Lafrans' },
    { fr: 'Je viens de Guadeloupe', cr: 'Mwen sòti Gwadloup' },
    { fr: 'Je viens de Martinique', cr: 'Mwen sòti Matinik' },
    { fr: 'Quelle heure est-il ?', cr: 'Ki lè i yé ?' },
    { fr: 'Il est quelle heure ?', cr: 'I ki lè ?' },
    { fr: 'Aujourd\'hui', cr: 'Jòdi' },
    { fr: 'Demain', cr: 'Dèmen' },
    { fr: 'Hier', cr: 'Yè' },
    { fr: 'Maintenant', cr: 'Kounnyé-a' },
    { fr: 'Plus tard', cr: 'Pli ta' },
    { fr: 'Bientôt', cr: 'Byento' },
    { fr: 'Toujours', cr: 'Toujou' },
    { fr: 'Jamais', cr: 'Jamé' },
    { fr: 'Peut-être', cr: 'Pétèt' },
    { fr: 'Bien sûr', cr: 'Byensir' },
    { fr: 'Évidemment', cr: 'Évidaman' },
    { fr: 'Attention !', cr: 'Atansyon !' },
    { fr: 'Au secours !', cr: 'Lèd mwen !' },
    { fr: 'Aide-moi !', cr: 'Ede mwen !' },
    { fr: 'Félicitations !', cr: 'Bravo !' },
    { fr: 'Bon courage', cr: 'Bon kouraj' },
    { fr: 'Bonne chance', cr: 'Bon chans' },
    { fr: 'Bon appétit', cr: 'Bon manj' },
    { fr: 'Santé ! (toast)', cr: 'Santé !' },
    { fr: 'Joyeux anniversaire', cr: 'Bon fèt' },
    { fr: 'Bonne année', cr: 'Bon lanné' },
    { fr: 'Joyeux Noël', cr: 'Jwayé Nwèl' },
    { fr: 'Bienvenue', cr: 'Byenvini' },
    { fr: 'Prends soin de toi', cr: 'Pwotéjé\'w' }
];
// ========================================
// PHRASES PAR THÈME (ENRICHIES)
// ========================================
const phrasesByTheme = {
    'À la maison': [
        { fr: 'Je suis à la maison', cr: 'Man ka kay' },
        { fr: 'Viens chez moi', cr: 'Vini kay mwen' },
        { fr: 'Où habites-tu ?', cr: 'Koté ou ka rété ?' },
        { fr: 'J\'habite en ville', cr: 'Man ka rété an vil' },
        { fr: 'J\'habite à la campagne', cr: 'Man ka rété an kanpay' },
        { fr: 'C\'est ma chambre', cr: 'Sa sé chanm mwen' },
        { fr: 'Ferme la porte', cr: 'Fèmen pòt-la' },
        { fr: 'Ouvre la fenêtre', cr: 'Ouvè fennet-la' },
        { fr: 'Allume la lumière', cr: 'Limyé lanp-la' },
        { fr: 'Éteins la lumière', cr: 'Éten lanp-la' },
        { fr: 'Je fais le ménage', cr: 'Man ka fè netwayaj' },
        { fr: 'Je cuisine', cr: 'Man ka kwit' }
    ],
    'Au restaurant': [
        { fr: 'Je voudrais commander', cr: 'Man lé kòmandé' },
        { fr: 'L\'addition s\'il vous plaît', cr: 'Lajisyon souplé' },
        { fr: 'C\'est très bon', cr: 'I bon anlo' },
        { fr: 'Je suis végétarien', cr: 'Man pa manjé vyann' },
        { fr: 'Qu\'est-ce que c\'est ?', cr: 'Sa ki sa ?' },
        { fr: 'Je prends ça', cr: 'Man pwan sa' },
        { fr: 'Une table pour deux', cr: 'An tab pou dé moun' },
        { fr: 'Vous avez une table libre ?', cr: 'Zot ni an tab lib ?' },
        { fr: 'Je voudrais boire quelque chose', cr: 'Man lé bwè an bagay' },
        { fr: 'C\'est épicé ?', cr: 'I piman ?' },
        { fr: 'Sans piment', cr: 'San piman' },
        { fr: 'Avec du piment', cr: 'Épi piman' }
    ],
    'Transports': [
        { fr: 'Où est l\'arrêt de bus ?', cr: 'Koté lariyet bis-la ?' },
        { fr: 'Je cherche un taxi', cr: 'Man ka chèché an taksi' },
        { fr: 'Combien coûte le ticket ?', cr: 'Konben tiké-a kouté ?' },
        { fr: 'Je vais à la plage', cr: 'Man ka alé praj' },
        { fr: 'Je vais en ville', cr: 'Man ka alé an vil' },
        { fr: 'C\'est loin ?', cr: 'Sa lwen ?' },
        { fr: 'C\'est proche', cr: 'Sa pré' },
        { fr: 'Arrêtez-vous ici', cr: 'Rété la' },
        { fr: 'Je descends ici', cr: 'Man ka désann la' },
        { fr: 'Tournez à gauche', cr: 'Viré agòch' },
        { fr: 'Tournez à droite', cr: 'Viré adwèt' },
        { fr: 'Continuez tout droit', cr: 'Kontiné tout dwèt' }
    ],
    'Faire du shopping': [
        { fr: 'Je cherche...', cr: 'Man ka chèché...' },
        { fr: 'Vous avez ça en bleu ?', cr: 'Zot ni sa an ble ?' },
        { fr: 'C\'est trop cher', cr: 'Sa twò chè' },
        { fr: 'Je peux essayer ?', cr: 'Man pé éséyé ?' },
        { fr: 'Quelle taille ?', cr: 'Ki grandè ?' },
        { fr: 'Je le prends', cr: 'Man pwan\'y' },
        { fr: 'Vous acceptez la carte ?', cr: 'Zot ka pwan kat ?' },
        { fr: 'C\'est combien ?', cr: 'Sa fè konben ?' },
        { fr: 'Vous pouvez faire un paquet cadeau ?', cr: 'Zot pé fè an paké kado ?' },
        { fr: 'Je regarde seulement', cr: 'Man ka gadé sèlman' },
        { fr: 'Vous avez d\'autres couleurs ?', cr: 'Zot ni dot koulè ?' }
    ],
    'Météo et nature': [
        { fr: 'Il fait beau', cr: 'I fè bèl tan' },
        { fr: 'Il fait chaud', cr: 'I fè cho' },
        { fr: 'Il pleut', cr: 'Lapli ka tombé' },
        { fr: 'Il y a du soleil', cr: 'Soley-la doubo' },
        { fr: 'Il y a du vent', cr: 'I ni van' },
        { fr: 'Il y a un orage', cr: 'I ni loraj' },
        { fr: 'La mer est belle', cr: 'Lanmè bèl' },
        { fr: 'La mer est agitée', cr: 'Lanmè ajité' },
        { fr: 'J\'aime la plage', cr: 'Mwen enmen praj' },
        { fr: 'J\'aime la montagne', cr: 'Mwen enmen mòn' },
        { fr: 'C\'est un beau paysage', cr: 'Sa sé an bèl peyizaj' },
        { fr: 'Il fait frais', cr: 'I fè fwè' }
    ],
    'Urgences': [
        { fr: 'J\'ai besoin d\'aide', cr: 'Mwen bizwen lèd' },
        { fr: 'Appelez un médecin', cr: 'Aplé an médsen' },
        { fr: 'Appelez la police', cr: 'Aplé lapolis' },
        { fr: 'Appelez les pompiers', cr: 'Aplé ponpyé yo' },
        { fr: 'Où est l\'hôpital ?', cr: 'Koté lopital ?' },
        { fr: 'Je suis malade', cr: 'Man malad' },
        { fr: 'J\'ai mal', cr: 'Mwen ni doulè' },
        { fr: 'J\'ai mal à la tête', cr: 'Tèt mwen ka fè mwen mal' },
        { fr: 'J\'ai mal au ventre', cr: 'Vant mwen ka fè mwen mal' },
        { fr: 'C\'est urgent', cr: 'Sa présan' },
        { fr: 'J\'ai perdu mes clés', cr: 'Man pèd kléyé mwen' },
        { fr: 'On m\'a volé mon sac', cr: 'Yo volé sak mwen' }
    ],
    'Au travail': [
        { fr: 'Je travaille', cr: 'Man ka travay' },
        { fr: 'Où travailles-tu ?', cr: 'Koté ou ka travay ?' },
        { fr: 'Je suis en réunion', cr: 'Man an réyinyon' },
        { fr: 'Je suis occupé', cr: 'Man okipé' },
        { fr: 'J\'ai du travail', cr: 'Man ni travay' },
        { fr: 'Je finis à quelle heure ?', cr: 'Man ka fini ki lè ?' },
        { fr: 'Bon travail', cr: 'Bon travay' },
        { fr: 'C\'est bien fait', cr: 'Sa bien fèt' }
    ],
    'Loisirs': [
        { fr: 'Tu veux jouer ?', cr: 'Ou lé jwé ?' },
        { fr: 'On va à la plage ?', cr: 'Nou ka alé praj ?' },
        { fr: 'J\'aime la musique', cr: 'Mwen enmen mizik' },
        { fr: 'J\'aime danser', cr: 'Mwen enmen dansé' },
        { fr: 'Tu danses ?', cr: 'Ou ka dansé ?' },
        { fr: 'C\'est la fête', cr: 'Sé fèt' },
        { fr: 'On s\'amuse bien', cr: 'Nou ka anbété bien' },
        { fr: 'Viens avec nous', cr: 'Vini épi nou' }
    ],
    'Sentiments': [
        { fr: 'Je suis content', cr: 'Man kontan' },
        { fr: 'Je suis triste', cr: 'Man tris' },
        { fr: 'Je suis en colère', cr: 'Man annkolè' },
        { fr: 'J\'ai peur', cr: 'Man pè' },
        { fr: 'Je suis surpris', cr: 'Man siprann' },
        { fr: 'Je suis désolé', cr: 'Man désòlé' },
        { fr: 'Je m\'excuse', cr: 'Man éskizé mwen' },
        { fr: 'Ne t\'inquiète pas', cr: 'Pa enkiyété\'w' },
        { fr: 'Ça va aller', cr: 'Sa ké bon' },
        { fr: 'Je comprends', cr: 'Man konprann' }
    ]
};
// ========================================
// MEGA DICTIONNAIRE ENRICHI (500+ mots)
// ========================================
const dictionary = [
    // FAMILLE ET PERSONNES
    { fr: 'Enfant', cr: 'Timoun', cat: 'Famille' },
    { fr: 'Bébé', cr: 'Tibébé', cat: 'Famille' },
    { fr: 'Homme', cr: 'Nonm', cat: 'Famille' },
    { fr: 'Femme', cr: 'Fanm', cat: 'Famille' },
    { fr: 'Garçon', cr: 'Tigason', cat: 'Famille' },
    { fr: 'Fille', cr: 'Tifi', cat: 'Famille' },
    { fr: 'Père', cr: 'Papa', cat: 'Famille' },
    { fr: 'Mère', cr: 'Manman', cat: 'Famille' },
    { fr: 'Frère', cr: 'Frè', cat: 'Famille' },
    { fr: 'Sœur', cr: 'Sè', cat: 'Famille' },
    { fr: 'Grand-mère', cr: 'Granmoun', cat: 'Famille' },
    { fr: 'Grand-père', cr: 'Granpapa', cat: 'Famille' },
    { fr: 'Oncle', cr: 'Tonton', cat: 'Famille' },
    { fr: 'Tante', cr: 'Tata', cat: 'Famille' },
    { fr: 'Cousin', cr: 'Kouzen', cat: 'Famille' },
    { fr: 'Cousine', cr: 'Kouzin', cat: 'Famille' },
    { fr: 'Neveu', cr: 'Nevé', cat: 'Famille' },
    { fr: 'Nièce', cr: 'Nyès', cat: 'Famille' },
    { fr: 'Mari', cr: 'Mari', cat: 'Famille' },
    { fr: 'Épouse', cr: 'Madanm', cat: 'Famille' },
    { fr: 'Ami', cr: 'Zanmi', cat: 'Famille' },
    { fr: 'Amie', cr: 'Zanmi', cat: 'Famille' },
    { fr: 'Voisin', cr: 'Vwazen', cat: 'Famille' },
    { fr: 'Voisine', cr: 'Vwazin', cat: 'Famille' },
    { fr: 'Gens', cr: 'Moun', cat: 'Famille' },
    { fr: 'Personne', cr: 'Moun', cat: 'Famille' },
    
    // LIEUX
    { fr: 'Maison', cr: 'Kay', cat: 'Lieux' },
    { fr: 'Chambre', cr: 'Chanm', cat: 'Lieux' },
    { fr: 'Cuisine', cr: 'Kizin', cat: 'Lieux' },
    { fr: 'Salle de bain', cr: 'Sal deben', cat: 'Lieux' },
    { fr: 'Salon', cr: 'Salon', cat: 'Lieux' },
    { fr: 'Jardin', cr: 'Jaden', cat: 'Lieux' },
    { fr: 'Porte', cr: 'Pòt', cat: 'Lieux' },
    { fr: 'Fenêtre', cr: 'Fennet', cat: 'Lieux' },
    { fr: 'Toit', cr: 'Twati', cat: 'Lieux' },
    { fr: 'Mur', cr: 'Miray', cat: 'Lieux' },
    { fr: 'École', cr: 'Lékòl', cat: 'Lieux' },
    { fr: 'Marché', cr: 'Maché', cat: 'Lieux' },
    { fr: 'Magasin', cr: 'Boutik', cat: 'Lieux' },
    { fr: 'Boutique', cr: 'Boutik', cat: 'Lieux' },
    { fr: 'Pharmacie', cr: 'Famasi', cat: 'Lieux' },
    { fr: 'Hôpital', cr: 'Lopital', cat: 'Lieux' },
    { fr: 'Église', cr: 'Legliz', cat: 'Lieux' },
    { fr: 'Plage', cr: 'Praj', cat: 'Lieux' },
    { fr: 'Mer', cr: 'Lanmè', cat: 'Lieux' },
    { fr: 'Montagne', cr: 'Mòn', cat: 'Lieux' },
    { fr: 'Forêt', cr: 'Foré', cat: 'Lieux' },
    { fr: 'Rivière', cr: 'Larivyè', cat: 'Lieux' },
    { fr: 'Ville', cr: 'Vil', cat: 'Lieux' },
    { fr: 'Village', cr: 'Bouk', cat: 'Lieux' },
    { fr: 'Campagne', cr: 'Kanpay', cat: 'Lieux' },
    { fr: 'Rue', cr: 'Lari', cat: 'Lieux' },
    { fr: 'Route', cr: 'Wout', cat: 'Lieux' },
    { fr: 'Chemin', cr: 'Chimen', cat: 'Lieux' },
    { fr: 'Pont', cr: 'Pon', cat: 'Lieux' },
    { fr: 'Aéroport', cr: 'Layopò', cat: 'Lieux' },
    { fr: 'Port', cr: 'Pò', cat: 'Lieux' },
    { fr: 'Gare', cr: 'Lagas', cat: 'Lieux' },
    { fr: 'Restaurant', cr: 'Restoran', cat: 'Lieux' },
    { fr: 'Bar', cr: 'Ba', cat: 'Lieux' },
    { fr: 'Hôtel', cr: 'Otèl', cat: 'Lieux' },
    { fr: 'Bureau', cr: 'Biwo', cat: 'Lieux' },
    { fr: 'Banque', cr: 'Bank', cat: 'Lieux' },
    { fr: 'Poste', cr: 'Lapòs', cat: 'Lieux' },
    
    // NOURRITURE ET BOISSONS
    { fr: 'Pain', cr: 'Pen', cat: 'Nourriture' },
    { fr: 'Eau', cr: 'Dlo', cat: 'Nourriture' },
    { fr: 'Riz', cr: 'Diri', cat: 'Nourriture' },
    { fr: 'Viande', cr: 'Vyann', cat: 'Nourriture' },
    { fr: 'Poisson', cr: 'Pwason', cat: 'Nourriture' },
    { fr: 'Poulet', cr: 'Poul', cat: 'Nourriture' },
    { fr: 'Porc', cr: 'Kochon', cat: 'Nourriture' },
    { fr: 'Bœuf', cr: 'Bèf', cat: 'Nourriture' },
    { fr: 'Crabe', cr: 'Krab', cat: 'Nourriture' },
    { fr: 'Crevette', cr: 'Kwivèt', cat: 'Nourriture' },
    { fr: 'Langouste', cr: 'Woumaw', cat: 'Nourriture' },
    { fr: 'Fruit', cr: 'Fwi', cat: 'Nourriture' },
    { fr: 'Légume', cr: 'Legim', cat: 'Nourriture' },
    { fr: 'Banane', cr: 'Fig', cat: 'Nourriture' },
    { fr: 'Plantain', cr: 'Bannann', cat: 'Nourriture' },
    { fr: 'Mangue', cr: 'Mango', cat: 'Nourriture' },
    { fr: 'Papaye', cr: 'Papay', cat: 'Nourriture' },
    { fr: 'Ananas', cr: 'Zanana', cat: 'Nourriture' },
    { fr: 'Coco', cr: 'Koko', cat: 'Nourriture' },
    { fr: 'Orange', cr: 'Zoranj', cat: 'Nourriture' },
    { fr: 'Citron', cr: 'Sitwon', cat: 'Nourriture' },
    { fr: 'Avocat', cr: 'Zaboka', cat: 'Nourriture' },
    { fr: 'Tomate', cr: 'Tomat', cat: 'Nourriture' },
    { fr: 'Salade', cr: 'Salad', cat: 'Nourriture' },
    { fr: 'Carotte', cr: 'Kawòt', cat: 'Nourriture' },
    { fr: 'Pomme de terre', cr: 'Patat', cat: 'Nourriture' },
    { fr: 'Igname', cr: 'Yanm', cat: 'Nourriture' },
    { fr: 'Patate douce', cr: 'Patat dis', cat: 'Nourriture' },
    { fr: 'Manioc', cr: 'Manyòk', cat: 'Nourriture' },
    { fr: 'Maïs', cr: 'Mayis', cat: 'Nourriture' },
    { fr: 'Haricot', cr: 'Pwa', cat: 'Nourriture' },
    { fr: 'Pois', cr: 'Pwa', cat: 'Nourriture' },
    { fr: 'Œuf', cr: 'Zé', cat: 'Nourriture' },
    { fr: 'Fromage', cr: 'Fwomaj', cat: 'Nourriture' },
    { fr: 'Beurre', cr: 'Bè', cat: 'Nourriture' },
    { fr: 'Lait', cr: 'Lèt', cat: 'Nourriture' },
    { fr: 'Sucre', cr: 'Sik', cat: 'Nourriture' },
    { fr: 'Sel', cr: 'Sèl', cat: 'Nourriture' },
    { fr: 'Poivre', cr: 'Pwav', cat: 'Nourriture' },
    { fr: 'Piment', cr: 'Piman', cat: 'Nourriture' },
    { fr: 'Ail', cr: 'Lay', cat: 'Nourriture' },
    { fr: 'Oignon', cr: 'Zonyon', cat: 'Nourriture' },
    { fr: 'Huile', cr: 'Lwil', cat: 'Nourriture' },
    { fr: 'Café', cr: 'Kfé', cat: 'Nourriture' },
    { fr: 'Thé', cr: 'Té', cat: 'Nourriture' },
    { fr: 'Jus', cr: 'Ji', cat: 'Nourriture' },
    { fr: 'Rhum', cr: 'Wonm', cat: 'Nourriture' },
    { fr: 'Bière', cr: 'Byè', cat: 'Nourriture' },
    { fr: 'Vin', cr: 'Ven', cat: 'Nourriture' },
    { fr: 'Gâteau', cr: 'Gato', cat: 'Nourriture' },
    { fr: 'Bonbon', cr: 'Bonbon', cat: 'Nourriture' },
    { fr: 'Chocolat', cr: 'Chokola', cat: 'Nourriture' },
    { fr: 'Glace', cr: 'Glas', cat: 'Nourriture' },
    
    // VERBES D'ACTION
    { fr: 'Être', cr: 'Yé', cat: 'Verbes' },
    { fr: 'Avoir', cr: 'Ni', cat: 'Verbes' },
    { fr: 'Faire', cr: 'Fè', cat: 'Verbes' },
    { fr: 'Dire', cr: 'Di', cat: 'Verbes' },
    { fr: 'Manger', cr: 'Manjé', cat: 'Verbes' },
    { fr: 'Boire', cr: 'Bwè', cat: 'Verbes' },
    { fr: 'Dormir', cr: 'Dòmi', cat: 'Verbes' },
    { fr: 'Parler', cr: 'Palé', cat: 'Verbes' },
    { fr: 'Écouter', cr: 'Tann', cat: 'Verbes' },
    { fr: 'Entendre', cr: 'Tann', cat: 'Verbes' },
    { fr: 'Voir', cr: 'Wè', cat: 'Verbes' },
    { fr: 'Regarder', cr: 'Gadé', cat: 'Verbes' },
    { fr: 'Comprendre', cr: 'Konprann', cat: 'Verbes' },
    { fr: 'Savoir', cr: 'Sav', cat: 'Verbes' },
    { fr: 'Connaître', cr: 'Konnet', cat: 'Verbes' },
    { fr: 'Pouvoir', cr: 'Pé', cat: 'Verbes' },
    { fr: 'Vouloir', cr: 'Lé', cat: 'Verbes' },
    { fr: 'Devoir', cr: 'Dwèt', cat: 'Verbes' },
    { fr: 'Aller', cr: 'Alé', cat: 'Verbes' },
    { fr: 'Venir', cr: 'Vini', cat: 'Verbes' },
    { fr: 'Arriver', cr: 'Rivé', cat: 'Verbes' },
    { fr: 'Partir', cr: 'Pati', cat: 'Verbes' },
    { fr: 'Sortir', cr: 'Sòti', cat: 'Verbes' },
    { fr: 'Entrer', cr: 'Antwé', cat: 'Verbes' },
    { fr: 'Rester', cr: 'Rété', cat: 'Verbes' },
    { fr: 'Revenir', cr: 'Tounen', cat: 'Verbes' },
    { fr: 'Retourner', cr: 'Retounen', cat: 'Verbes' },
    { fr: 'Monter', cr: 'Monté', cat: 'Verbes' },
    { fr: 'Descendre', cr: 'Désann', cat: 'Verbes' },
    { fr: 'Tomber', cr: 'Tonmé', cat: 'Verbes' },
    { fr: 'Lever', cr: 'Lévé', cat: 'Verbes' },
    { fr: 'Asseoir', cr: 'Chita', cat: 'Verbes' },
    { fr: 'Coucher', cr: 'Kouché', cat: 'Verbes' },
    { fr: 'Chercher', cr: 'Chèché', cat: 'Verbes' },
    { fr: 'Trouver', cr: 'Jwenn', cat: 'Verbes' },
    { fr: 'Perdre', cr: 'Pèd', cat: 'Verbes' },
    { fr: 'Prendre', cr: 'Pwan', cat: 'Verbes' },
    { fr: 'Donner', cr: 'Bay', cat: 'Verbes' },
    { fr: 'Recevoir', cr: 'Résévwè', cat: 'Verbes' },
    { fr: 'Garder', cr: 'Gadé', cat: 'Verbes' },
    { fr: 'Laisser', cr: 'Kité', cat: 'Verbes' },
    { fr: 'Mettre', cr: 'Mété', cat: 'Verbes' },
    { fr: 'Poser', cr: 'Pozé', cat: 'Verbes' },
    { fr: 'Enlever', cr: 'Enlevé', cat: 'Verbes' },
    { fr: 'Tirer', cr: 'Tiré', cat: 'Verbes' },
    { fr: 'Pousser', cr: 'Pousé', cat: 'Verbes' },
    { fr: 'Porter', cr: 'Pòté', cat: 'Verbes' },
    { fr: 'Tenir', cr: 'Tini', cat: 'Verbes' },
    { fr: 'Toucher', cr: 'Touché', cat: 'Verbes' },
    { fr: 'Aimer', cr: 'Enmen', cat: 'Verbes' },
    { fr: 'Détester', cr: 'Rayi', cat: 'Verbes' },
    { fr: 'Préférer', cr: 'Préféré', cat: 'Verbes' },
    { fr: 'Penser', cr: 'Pansé', cat: 'Verbes' },
    { fr: 'Croire', cr: 'Kwè', cat: 'Verbes' },
    { fr: 'Oublier', cr: 'Bliyé', cat: 'Verbes' },
    { fr: 'Se souvenir', cr: 'Sonjé', cat: 'Verbes' },
    { fr: 'Apprendre', cr: 'Aprann', cat: 'Verbes' },
    { fr: 'Enseigner', cr: 'Ansenyen', cat: 'Verbes' },
    { fr: 'Étudier', cr: 'Étidyé', cat: 'Verbes' },
    { fr: 'Lire', cr: 'Li', cat: 'Verbes' },
    { fr: 'Écrire', cr: 'Ékri', cat: 'Verbes' },
    { fr: 'Compter', cr: 'Konté', cat: 'Verbes' },
    { fr: 'Calculer', cr: 'Kalkilé', cat: 'Verbes' },
    { fr: 'Travailler', cr: 'Travay', cat: 'Verbes' },
    { fr: 'Jouer', cr: 'Jwé', cat: 'Verbes' },
    { fr: 'Danser', cr: 'Dansé', cat: 'Verbes' },
    { fr: 'Chanter', cr: 'Chanté', cat: 'Verbes' },
    { fr: 'Rire', cr: 'Ri', cat: 'Verbes' },
    { fr: 'Pleurer', cr: 'Pléré', cat: 'Verbes' },
    { fr: 'Crier', cr: 'Kryé', cat: 'Verbes' },
    { fr: 'Appeler', cr: 'Aplé', cat: 'Verbes' },
    { fr: 'Répondre', cr: 'Réponn', cat: 'Verbes' },
    { fr: 'Demander', cr: 'Mandé', cat: 'Verbes' },
    { fr: 'Marcher', cr: 'Maché', cat: 'Verbes' },
    { fr: 'Courir', cr: 'Kouri', cat: 'Verbes' },
    { fr: 'Sauter', cr: 'Soté', cat: 'Verbes' },
    { fr: 'Nager', cr: 'Najé', cat: 'Verbes' },
    { fr: 'Voler', cr: 'Volé', cat: 'Verbes' },
    { fr: 'Conduire', cr: 'Kondwi', cat: 'Verbes' },
    { fr: 'Voyager', cr: 'Voyajé', cat: 'Verbes' },
    { fr: 'Acheter', cr: 'Achté', cat: 'Verbes' },
    { fr: 'Vendre', cr: 'Vann', cat: 'Verbes' },
    { fr: 'Payer', cr: 'Peyé', cat: 'Verbes' },
    { fr: 'Coûter', cr: 'Kouté', cat: 'Verbes' },
    { fr: 'Gagner', cr: 'Gannyé', cat: 'Verbes' },
    { fr: 'Dépenser', cr: 'Dépansé', cat: 'Verbes' },
    { fr: 'Économiser', cr: 'Ekonomizé', cat: 'Verbes' },
    { fr: 'Ouvrir', cr: 'Ouvè', cat: 'Verbes' },
    { fr: 'Fermer', cr: 'Fèmen', cat: 'Verbes' },
    { fr: 'Commencer', cr: 'Koumansé', cat: 'Verbes' },
    { fr: 'Finir', cr: 'Fini', cat: 'Verbes' },
    { fr: 'Arrêter', cr: 'Rété', cat: 'Verbes' },
    { fr: 'Continuer', cr: 'Kontiné', cat: 'Verbes' },
    { fr: 'Attendre', cr: 'Atann', cat: 'Verbes' },
    { fr: 'Aider', cr: 'Ede', cat: 'Verbes' },
    { fr: 'Montrer', cr: 'Montré', cat: 'Verbes' },
    { fr: 'Expliquer', cr: 'Espliké', cat: 'Verbes' },
    { fr: 'Casser', cr: 'Kasé', cat: 'Verbes' },
    { fr: 'Réparer', cr: 'Réparé', cat: 'Verbes' },
    { fr: 'Construire', cr: 'Bati', cat: 'Verbes' },
    { fr: 'Détruire', cr: 'Détwi', cat: 'Verbes' },
    { fr: 'Nettoyer', cr: 'Netwayé', cat: 'Verbes' },
    { fr: 'Laver', cr: 'Lavé', cat: 'Verbes' },
    { fr: 'Sécher', cr: 'Séché', cat: 'Verbes' },
    { fr: 'Cuisiner', cr: 'Kwit', cat: 'Verbes' },
    { fr: 'Préparer', cr: 'Préparé', cat: 'Verbes' },
    { fr: 'Couper', cr: 'Koupé', cat: 'Verbes' },
    { fr: 'Mélanger', cr: 'Mélanjé', cat: 'Verbes' },
// ADJECTIFS
    { fr: 'Grand', cr: 'Gwo', cat: 'Adjectifs' },
    { fr: 'Petit', cr: 'Ti', cat: 'Adjectifs' },
    { fr: 'Gros', cr: 'Gwo', cat: 'Adjectifs' },
    { fr: 'Mince', cr: 'Mèg', cat: 'Adjectifs' },
    { fr: 'Long', cr: 'Long', cat: 'Adjectifs' },
    { fr: 'Court', cr: 'Kout', cat: 'Adjectifs' },
    { fr: 'Large', cr: 'Laj', cat: 'Adjectifs' },
    { fr: 'Étroit', cr: 'Stwa', cat: 'Adjectifs' },
    { fr: 'Haut', cr: 'Wo', cat: 'Adjectifs' },
    { fr: 'Bas', cr: 'Ba', cat: 'Adjectifs' },
    { fr: 'Profond', cr: 'Fon', cat: 'Adjectifs' },
    { fr: 'Beau', cr: 'Bèl', cat: 'Adjectifs' },
    { fr: 'Belle', cr: 'Bèl', cat: 'Adjectifs' },
    { fr: 'Joli', cr: 'Joli', cat: 'Adjectifs' },
    { fr: 'Laid', cr: 'Lèd', cat: 'Adjectifs' },
    { fr: 'Vieux', cr: 'Vyé', cat: 'Adjectifs' },
    { fr: 'Jeune', cr: 'Jenn', cat: 'Adjectifs' },
    { fr: 'Nouveau', cr: 'Nèf', cat: 'Adjectifs' },
    { fr: 'Ancien', cr: 'Ansyen', cat: 'Adjectifs' },
    { fr: 'Moderne', cr: 'Modèn', cat: 'Adjectifs' },
    { fr: 'Bon', cr: 'Bon', cat: 'Adjectifs' },
    { fr: 'Mauvais', cr: 'Move', cat: 'Adjectifs' },
    { fr: 'Bien', cr: 'Byen', cat: 'Adjectifs' },
    { fr: 'Mal', cr: 'Mal', cat: 'Adjectifs' },
    { fr: 'Meilleur', cr: 'Meyè', cat: 'Adjectifs' },
    { fr: 'Pire', cr: 'Pi mal', cat: 'Adjectifs' },
    { fr: 'Chaud', cr: 'Cho', cat: 'Adjectifs' },
    { fr: 'Froid', cr: 'Frèt', cat: 'Adjectifs' },
    { fr: 'Tiède', cr: 'Tyèd', cat: 'Adjectifs' },
    { fr: 'Frais', cr: 'Fwè', cat: 'Adjectifs' },
    { fr: 'Doux', cr: 'Dou', cat: 'Adjectifs' },
    { fr: 'Dur', cr: 'Di', cat: 'Adjectifs' },
    { fr: 'Mou', cr: 'Mou', cat: 'Adjectifs' },
    { fr: 'Sec', cr: 'Sèk', cat: 'Adjectifs' },
    { fr: 'Mouillé', cr: 'Mouyé', cat: 'Adjectifs' },
    { fr: 'Humide', cr: 'Imid', cat: 'Adjectifs' },
    { fr: 'Sale', cr: 'Sal', cat: 'Adjectifs' },
    { fr: 'Propre', cr: 'Pwòp', cat: 'Adjectifs' },
    { fr: 'Clair', cr: 'Klè', cat: 'Adjectifs' },
    { fr: 'Sombre', cr: 'Sonm', cat: 'Adjectifs' },
    { fr: 'Lumineux', cr: 'Liminyé', cat: 'Adjectifs' },
    { fr: 'Obscur', cr: 'Fonnwè', cat: 'Adjectifs' },
    { fr: 'Plein', cr: 'Plen', cat: 'Adjectifs' },
    { fr: 'Vide', cr: 'Vid', cat: 'Adjectifs' },
    { fr: 'Lourd', cr: 'Lou', cat: 'Adjectifs' },
    { fr: 'Léger', cr: 'Léjè', cat: 'Adjectifs' },
    { fr: 'Fort', cr: 'Fò', cat: 'Adjectifs' },
    { fr: 'Faible', cr: 'Fèb', cat: 'Adjectifs' },
    { fr: 'Puissant', cr: 'Pwisan', cat: 'Adjectifs' },
    { fr: 'Content', cr: 'Kontan', cat: 'Adjectifs' },
    { fr: 'Heureux', cr: 'Eré', cat: 'Adjectifs' },
    { fr: 'Triste', cr: 'Tris', cat: 'Adjectifs' },
    { fr: 'Joyeux', cr: 'Jwayyé', cat: 'Adjectifs' },
    { fr: 'Fâché', cr: 'Faché', cat: 'Adjectifs' },
    { fr: 'En colère', cr: 'Annkolè', cat: 'Adjectifs' },
    { fr: 'Calme', cr: 'Kalm', cat: 'Adjectifs' },
    { fr: 'Nerveux', cr: 'Nèvé', cat: 'Adjectifs' },
    { fr: 'Fatigué', cr: 'Las', cat: 'Adjectifs' },
    { fr: 'Reposé', cr: 'Riposé', cat: 'Adjectifs' },
    { fr: 'Malade', cr: 'Malad', cat: 'Adjectifs' },
    { fr: 'En bonne santé', cr: 'An santé', cat: 'Adjectifs' },
    { fr: 'Vivant', cr: 'Vivan', cat: 'Adjectifs' },
    { fr: 'Mort', cr: 'Mò', cat: 'Adjectifs' },
    { fr: 'Libre', cr: 'Lib', cat: 'Adjectifs' },
    { fr: 'Occupé', cr: 'Okipé', cat: 'Adjectifs' },
    { fr: 'Disponible', cr: 'Disponib', cat: 'Adjectifs' },
    { fr: 'Facile', cr: 'Fasil', cat: 'Adjectifs' },
    { fr: 'Difficile', cr: 'Difisil', cat: 'Adjectifs' },
    { fr: 'Simple', cr: 'Senp', cat: 'Adjectifs' },
    { fr: 'Compliqué', cr: 'Konpliké', cat: 'Adjectifs' },
    { fr: 'Rapide', cr: 'Vit', cat: 'Adjectifs' },
    { fr: 'Lent', cr: 'Dousman', cat: 'Adjectifs' },
    { fr: 'Tôt', cr: 'Bonè', cat: 'Adjectifs' },
    { fr: 'Tard', cr: 'Ta', cat: 'Adjectifs' },
    { fr: 'Proche', cr: 'Pré', cat: 'Adjectifs' },
    { fr: 'Loin', cr: 'Lwen', cat: 'Adjectifs' },
    { fr: 'Cher', cr: 'Chè', cat: 'Adjectifs' },
    { fr: 'Bon marché', cr: 'Pa chè', cat: 'Adjectifs' },
    { fr: 'Riche', cr: 'Rich', cat: 'Adjectifs' },
    { fr: 'Pauvre', cr: 'Pòv', cat: 'Adjectifs' },
    { fr: 'Gentil', cr: 'Janti', cat: 'Adjectifs' },
    { fr: 'Méchant', cr: 'Mechan', cat: 'Adjectifs' },
    { fr: 'Intelligent', cr: 'Entèlijan', cat: 'Adjectifs' },
    { fr: 'Bête', cr: 'Bèt', cat: 'Adjectifs' },
    { fr: 'Sage', cr: 'Saj', cat: 'Adjectifs' },
    { fr: 'Fou', cr: 'Fou', cat: 'Adjectifs' },
    { fr: 'Courageux', cr: 'Kourajé', cat: 'Adjectifs' },
    { fr: 'Peureux', cr: 'Pèrè', cat: 'Adjectifs' },
    { fr: 'Timide', cr: 'Timid', cat: 'Adjectifs' },
    { fr: 'Confiant', cr: 'Konfyan', cat: 'Adjectifs' },
    { fr: 'Poli', cr: 'Poli', cat: 'Adjectifs' },
    { fr: 'Impoli', cr: 'Enpoli', cat: 'Adjectifs' },
    { fr: 'Honnête', cr: 'Onèt', cat: 'Adjectifs' },
    { fr: 'Malhonnête', cr: 'Malonèt', cat: 'Adjectifs' },
    
    // COULEURS
    { fr: 'Rouge', cr: 'Rouj', cat: 'Couleurs' },
    { fr: 'Bleu', cr: 'Ble', cat: 'Couleurs' },
    { fr: 'Vert', cr: 'Vè', cat: 'Couleurs' },
    { fr: 'Jaune', cr: 'Jòn', cat: 'Couleurs' },
    { fr: 'Orange', cr: 'Oranj', cat: 'Couleurs' },
    { fr: 'Violet', cr: 'Vyolè', cat: 'Couleurs' },
    { fr: 'Rose', cr: 'Woz', cat: 'Couleurs' },
    { fr: 'Blanc', cr: 'Blan', cat: 'Couleurs' },
    { fr: 'Noir', cr: 'Nwè', cat: 'Couleurs' },
    { fr: 'Gris', cr: 'Gri', cat: 'Couleurs' },
    { fr: 'Marron', cr: 'Mawon', cat: 'Couleurs' },
    { fr: 'Brun', cr: 'Bren', cat: 'Couleurs' },
    { fr: 'Beige', cr: 'Bèj', cat: 'Couleurs' },
    
    // TEMPS ET MOMENTS
    { fr: 'Jour', cr: 'Jou', cat: 'Temps' },
    { fr: 'Nuit', cr: 'Nwit', cat: 'Temps' },
    { fr: 'Matin', cr: 'Maten', cat: 'Temps' },
    { fr: 'Midi', cr: 'Midi', cat: 'Temps' },
    { fr: 'Après-midi', cr: 'Aprémidi', cat: 'Temps' },
    { fr: 'Soir', cr: 'Aswè', cat: 'Temps' },
    { fr: 'Minuit', cr: 'Minwit', cat: 'Temps' },
    { fr: 'Aube', cr: 'Lòb', cat: 'Temps' },
    { fr: 'Crépuscule', cr: 'Krépiské', cat: 'Temps' },
    { fr: 'Aujourd\'hui', cr: 'Jòdi', cat: 'Temps' },
    { fr: 'Demain', cr: 'Dèmen', cat: 'Temps' },
    { fr: 'Hier', cr: 'Yè', cat: 'Temps' },
    { fr: 'Avant-hier', cr: 'Avan yè', cat: 'Temps' },
    { fr: 'Après-demain', cr: 'Aprè dèmen', cat: 'Temps' },
    { fr: 'Maintenant', cr: 'Kounnyé-a', cat: 'Temps' },
    { fr: 'Tout de suite', cr: 'Tousuit', cat: 'Temps' },
    { fr: 'Bientôt', cr: 'Byento', cat: 'Temps' },
    { fr: 'Plus tard', cr: 'Pli ta', cat: 'Temps' },
    { fr: 'Avant', cr: 'Avan', cat: 'Temps' },
    { fr: 'Après', cr: 'Aprè', cat: 'Temps' },
    { fr: 'Pendant', cr: 'Pandan', cat: 'Temps' },
    { fr: 'Toujours', cr: 'Toujou', cat: 'Temps' },
    { fr: 'Jamais', cr: 'Jamé', cat: 'Temps' },
    { fr: 'Souvent', cr: 'Souvan', cat: 'Temps' },
    { fr: 'Parfois', cr: 'Parfwa', cat: 'Temps' },
    { fr: 'Rarement', cr: 'Raman', cat: 'Temps' },
    { fr: 'Longtemps', cr: 'Lontan', cat: 'Temps' },
    { fr: 'Semaine', cr: 'Semenn', cat: 'Temps' },
    { fr: 'Mois', cr: 'Mwa', cat: 'Temps' },
    { fr: 'Année', cr: 'Lanné', cat: 'Temps' },
    { fr: 'Heure', cr: 'Lè', cat: 'Temps' },
    { fr: 'Minute', cr: 'Minit', cat: 'Temps' },
    { fr: 'Seconde', cr: 'Segond', cat: 'Temps' },
    
    // JOURS DE LA SEMAINE
    { fr: 'Lundi', cr: 'Lendi', cat: 'Temps' },
    { fr: 'Mardi', cr: 'Madi', cat: 'Temps' },
    { fr: 'Mercredi', cr: 'Mèkredi', cat: 'Temps' },
    { fr: 'Jeudi', cr: 'Jédi', cat: 'Temps' },
    { fr: 'Vendredi', cr: 'Vandredi', cat: 'Temps' },
    { fr: 'Samedi', cr: 'Sanmdi', cat: 'Temps' },
    { fr: 'Dimanche', cr: 'Dimanch', cat: 'Temps' },
    
    // MOIS DE L'ANNÉE
    { fr: 'Janvier', cr: 'Janvyé', cat: 'Temps' },
    { fr: 'Février', cr: 'Févryé', cat: 'Temps' },
    { fr: 'Mars', cr: 'Mas', cat: 'Temps' },
    { fr: 'Avril', cr: 'Avril', cat: 'Temps' },
    { fr: 'Mai', cr: 'Mé', cat: 'Temps' },
    { fr: 'Juin', cr: 'Jwen', cat: 'Temps' },
    { fr: 'Juillet', cr: 'Jiyè', cat: 'Temps' },
    { fr: 'Août', cr: 'Out', cat: 'Temps' },
    { fr: 'Septembre', cr: 'Sèptanm', cat: 'Temps' },
    { fr: 'Octobre', cr: 'Oktòb', cat: 'Temps' },
    { fr: 'Novembre', cr: 'Novanm', cat: 'Temps' },
    { fr: 'Décembre', cr: 'Désanm', cat: 'Temps' },
    
    // NOMBRES
    { fr: 'Zéro', cr: 'Zéwo', cat: 'Nombres' },
    { fr: 'Un', cr: 'An', cat: 'Nombres' },
    { fr: 'Deux', cr: 'Dé', cat: 'Nombres' },
    { fr: 'Trois', cr: 'Twa', cat: 'Nombres' },
    { fr: 'Quatre', cr: 'Kat', cat: 'Nombres' },
    { fr: 'Cinq', cr: 'Senk', cat: 'Nombres' },
    { fr: 'Six', cr: 'Sis', cat: 'Nombres' },
    { fr: 'Sept', cr: 'Sèt', cat: 'Nombres' },
    { fr: 'Huit', cr: 'Wit', cat: 'Nombres' },
    { fr: 'Neuf', cr: 'Nèf', cat: 'Nombres' },
    { fr: 'Dix', cr: 'Dis', cat: 'Nombres' },
    { fr: 'Onze', cr: 'Onz', cat: 'Nombres' },
    { fr: 'Douze', cr: 'Douz', cat: 'Nombres' },
    { fr: 'Treize', cr: 'Trèz', cat: 'Nombres' },
    { fr: 'Quatorze', cr: 'Katòz', cat: 'Nombres' },
    { fr: 'Quinze', cr: 'Kenz', cat: 'Nombres' },
    { fr: 'Seize', cr: 'Sèz', cat: 'Nombres' },
    { fr: 'Vingt', cr: 'Ven', cat: 'Nombres' },
    { fr: 'Trente', cr: 'Trant', cat: 'Nombres' },
    { fr: 'Quarante', cr: 'Karant', cat: 'Nombres' },
    { fr: 'Cinquante', cr: 'Senkant', cat: 'Nombres' },
    { fr: 'Soixante', cr: 'Swasant', cat: 'Nombres' },
    { fr: 'Cent', cr: 'San', cat: 'Nombres' },
    { fr: 'Mille', cr: 'Mil', cat: 'Nombres' },
    { fr: 'Million', cr: 'Milyon', cat: 'Nombres' },
    { fr: 'Premier', cr: 'Prémyé', cat: 'Nombres' },
    { fr: 'Deuxième', cr: 'Dézyèm', cat: 'Nombres' },
    { fr: 'Dernier', cr: 'Dènyé', cat: 'Nombres' },
    
    // CORPS HUMAIN
    { fr: 'Corps', cr: 'Kò', cat: 'Corps' },
    { fr: 'Tête', cr: 'Tèt', cat: 'Corps' },
    { fr: 'Cheveux', cr: 'Chivé', cat: 'Corps' },
    { fr: 'Visage', cr: 'Figi', cat: 'Corps' },
    { fr: 'Front', cr: 'Fwon', cat: 'Corps' },
    { fr: 'Œil', cr: 'Zié', cat: 'Corps' },
    { fr: 'Yeux', cr: 'Zié', cat: 'Corps' },
    { fr: 'Nez', cr: 'Nen', cat: 'Corps' },
    { fr: 'Bouche', cr: 'Bouch', cat: 'Corps' },
    { fr: 'Lèvre', cr: 'Lèv', cat: 'Corps' },
    { fr: 'Dent', cr: 'Dan', cat: 'Corps' },
    { fr: 'Langue', cr: 'Lang', cat: 'Corps' },
    { fr: 'Oreille', cr: 'Zòrèy', cat: 'Corps' },
    { fr: 'Joue', cr: 'Jou', cat: 'Corps' },
    { fr: 'Menton', cr: 'Manton', cat: 'Corps' },
    { fr: 'Cou', cr: 'Kou', cat: 'Corps' },
    { fr: 'Épaule', cr: 'Zépòl', cat: 'Corps' },
    { fr: 'Bras', cr: 'Bra', cat: 'Corps' },
    { fr: 'Coude', cr: 'Koud', cat: 'Corps' },
    { fr: 'Main', cr: 'Men', cat: 'Corps' },
    { fr: 'Doigt', cr: 'Dwèt', cat: 'Corps' },
    { fr: 'Ongle', cr: 'Zong', cat: 'Corps' },
    { fr: 'Poitrine', cr: 'Lestomak', cat: 'Corps' },
    { fr: 'Ventre', cr: 'Vant', cat: 'Corps' },
    { fr: 'Dos', cr: 'Do', cat: 'Corps' },
    { fr: 'Fesse', cr: 'Fès', cat: 'Corps' },
    { fr: 'Jambe', cr: 'Janm', cat: 'Corps' },
    { fr: 'Genou', cr: 'Jenou', cat: 'Corps' },
    { fr: 'Pied', cr: 'Pyé', cat: 'Corps' },
    { fr: 'Orteil', cr: 'Zòtèy', cat: 'Corps' },
    { fr: 'Peau', cr: 'Po', cat: 'Corps' },
    { fr: 'Os', cr: 'Zo', cat: 'Corps' },
    { fr: 'Sang', cr: 'San', cat: 'Corps' },
    { fr: 'Cœur', cr: 'Kè', cat: 'Corps' },
    
    // ANIMAUX
    { fr: 'Animal', cr: 'Bèt', cat: 'Animaux' },
    { fr: 'Chien', cr: 'Chen', cat: 'Animaux' },
    { fr: 'Chat', cr: 'Chat', cat: 'Animaux' },
    { fr: 'Oiseau', cr: 'Zwezo', cat: 'Animaux' },
    { fr: 'Poisson', cr: 'Pwason', cat: 'Animaux' },
    { fr: 'Cheval', cr: 'Chouval', cat: 'Animaux' },
    { fr: 'Vache', cr: 'Vach', cat: 'Animaux' },
    { fr: 'Cochon', cr: 'Kochon', cat: 'Animaux' },
    { fr: 'Poule', cr: 'Poul', cat: 'Animaux' },
    { fr: 'Coq', cr: 'Kòk', cat: 'Animaux' },
    { fr: 'Canard', cr: 'Kanna', cat: 'Animaux' },
    { fr: 'Mouton', cr: 'Mouton', cat: 'Animaux' },
    { fr: 'Chèvre', cr: 'Kabrit', cat: 'Animaux' },
    { fr: 'Âne', cr: 'Bourik', cat: 'Animaux' },
    { fr: 'Rat', cr: 'Rat', cat: 'Animaux' },
    { fr: 'Souris', cr: 'Souri', cat: 'Animaux' },
    { fr: 'Serpent', cr: 'Sèpan', cat: 'Animaux' },
    { fr: 'Tortue', cr: 'Tòti', cat: 'Animaux' },
    { fr: 'Crabe', cr: 'Krab', cat: 'Animaux' },
    { fr: 'Papillon', cr: 'Papiyon', cat: 'Animaux' },
    { fr: 'Mouche', cr: 'Mouch', cat: 'Animaux' },
    { fr: 'Moustique', cr: 'Maringouen', cat: 'Animaux' },
    { fr: 'Araignée', cr: 'Zarenyen', cat: 'Animaux' },
    { fr: 'Fourmi', cr: 'Foumi', cat: 'Animaux' },
    
    // OBJETS DE LA MAISON
    { fr: 'Table', cr: 'Tab', cat: 'Objets' },
    { fr: 'Chaise', cr: 'Chèz', cat: 'Objets' },
    { fr: 'Lit', cr: 'Kabann', cat: 'Objets' },
    { fr: 'Armoire', cr: 'Amwè', cat: 'Objets' },
    { fr: 'Étagère', cr: 'Étajè', cat: 'Objets' },
    { fr: 'Miroir', cr: 'Glas', cat: 'Objets' },
    { fr: 'Lampe', cr: 'Lanp', cat: 'Objets' },
    { fr: 'Rideau', cr: 'Rido', cat: 'Objets' },
    { fr: 'Tapis', cr: 'Tapi', cat: 'Objets' },
    { fr: 'Coussin', cr: 'Kousen', cat: 'Objets' },
    { fr: 'Couverture', cr: 'Kouvèti', cat: 'Objets' },
    { fr: 'Oreiller', cr: 'Zòrèyè', cat: 'Objets' },
    { fr: 'Assiette', cr: 'Asyèt', cat: 'Objets' },
    { fr: 'Verre', cr: 'Vè', cat: 'Objets' },
    { fr: 'Tasse', cr: 'Tas', cat: 'Objets' },
    { fr: 'Fourchette', cr: 'Fouchèt', cat: 'Objets' },
    { fr: 'Couteau', cr: 'Kouto', cat: 'Objets' },
    { fr: 'Cuillère', cr: 'Kiyè', cat: 'Objets' },
    { fr: 'Casserole', cr: 'Kasròl', cat: 'Objets' },
    { fr: 'Poêle', cr: 'Lapwèl', cat: 'Objets' },
    { fr: 'Bouteille', cr: 'Boutèy', cat: 'Objets' },
    { fr: 'Sac', cr: 'Sak', cat: 'Objets' },
    { fr: 'Boîte', cr: 'Bwèt', cat: 'Objets' },
    { fr: 'Clé', cr: 'Klé', cat: 'Objets' },
    { fr: 'Téléphone', cr: 'Téléfòn', cat: 'Objets' },
    { fr: 'Livre', cr: 'Liv', cat: 'Objets' },
    { fr: 'Stylo', cr: 'Plim', cat: 'Objets' },
    { fr: 'Papier', cr: 'Papyé', cat: 'Objets' },
    { fr: 'Montre', cr: 'Mont', cat: 'Objets' },
    { fr: 'Lunettes', cr: 'Linèt', cat: 'Objets' },
    
    // VÊTEMENTS
    { fr: 'Vêtement', cr: 'Rad', cat: 'Vêtements' },
    { fr: 'Chemise', cr: 'Chimiz', cat: 'Vêtements' },
    { fr: 'Pantalon', cr: 'Pantalon', cat: 'Vêtements' },
    { fr: 'Robe', cr: 'Wòb', cat: 'Vêtements' },
    { fr: 'Jupe', cr: 'Jip', cat: 'Vêtements' },
    { fr: 'Short', cr: 'Chòt', cat: 'Vêtements' },
    { fr: 'Chaussure', cr: 'Soulié', cat: 'Vêtements' },
    { fr: 'Sandale', cr: 'Sandal', cat: 'Vêtements' },
    { fr: 'Chapeau', cr: 'Chapo', cat: 'Vêtements' },
    { fr: 'Casquette', cr: 'Kaskèt', cat: 'Vêtements' },
    { fr: 'Ceinture', cr: 'Sent', cat: 'Vêtements' },
    { fr: 'Chaussette', cr: 'Chosèt', cat: 'Vêtements' },
    
    // MÉTÉO
    { fr: 'Soleil', cr: 'Soley', cat: 'Météo' }, { fr: 'Lune', cr: 'Lalin', cat: 'Météo' }, { fr: 'Étoile', cr: 'Zetwal', cat: 'Météo' }, { fr: 'Nuage', cr: 'Niaj', cat: 'Météo' }, { fr: 'Pluie', cr: 'Lapli', cat: 'Météo' }, { fr: 'Vent', cr: 'Van', cat: 'Météo' }, { fr: 'Orage', cr: 'Loraj', cat: 'Météo' }, { fr: 'Tonnerre', cr: 'Tonnè', cat: 'Météo' }, { fr: 'Éclair', cr: 'Zèklè', cat: 'Météo' }, { fr: 'Cyclone', cr: 'Siklon', cat: 'Météo' }, { fr: 'Ouragan', cr: 'Ouragan', cat: 'Météo' }, { fr: 'Arc-en-ciel', cr: 'Lakansyèl', cat: 'Météo' },
// MOTS DIVERS UTILES
{ fr: 'Chose', cr: 'Bagay', cat: 'Divers' },
{ fr: 'Temps', cr: 'Tan', cat: 'Divers' },
{ fr: 'Vie', cr: 'Lavi', cat: 'Divers' },
{ fr: 'Mort', cr: 'Lanmò', cat: 'Divers' },
{ fr: 'Monde', cr: 'Lemond', cat: 'Divers' },
{ fr: 'Pays', cr: 'Péyi', cat: 'Divers' },
{ fr: 'Île', cr: 'Zil', cat: 'Divers' },
{ fr: 'Argent', cr: 'Lajan', cat: 'Divers' },
{ fr: 'Travail', cr: 'Travay', cat: 'Divers' },
{ fr: 'Problème', cr: 'Pwoblèm', cat: 'Divers' },
{ fr: 'Question', cr: 'Kesyon', cat: 'Divers' },
{ fr: 'Réponse', cr: 'Répons', cat: 'Divers' },
{ fr: 'Histoire', cr: 'Istwa', cat: 'Divers' },
{ fr: 'Nom', cr: 'Non', cat: 'Divers' },
{ fr: 'Parole', cr: 'Pawòl', cat: 'Divers' },
{ fr: 'Voix', cr: 'Vwa', cat: 'Divers' },
{ fr: 'Son', cr: 'Son', cat: 'Divers' },
{ fr: 'Bruit', cr: 'Bwi', cat: 'Divers' },
{ fr: 'Musique', cr: 'Mizik', cat: 'Divers' },
{ fr: 'Chanson', cr: 'Chansòn', cat: 'Divers' },
{ fr: 'Fête', cr: 'Fèt', cat: 'Divers' },
{ fr: 'Cadeau', cr: 'Kado', cat: 'Divers' },
{ fr: 'Amour', cr: 'Lanmou', cat: 'Divers' },
{ fr: 'Paix', cr: 'Lapé', cat: 'Divers' },
{ fr: 'Guerre', cr: 'Lagè', cat: 'Divers' },
{ fr: 'Force', cr: 'Fòs', cat: 'Divers' },
{ fr: 'Courage', cr: 'Kouraj', cat: 'Divers' },
{ fr: 'Chance', cr: 'Chans', cat: 'Divers' },
{ fr: 'Vérité', cr: 'Vérité', cat: 'Divers' },
{ fr: 'Mensonge', cr: 'Mantè', cat: 'Divers' }
];
// ========================================
// 20+ DEVINETTES CRÉOLES
// ========================================
const riddles = [
    { 
        expr: 'Chapo fey', 
        hint: 'Expression pour dire qu\'il pleut fort', 
        answer: 'Il pleut des cordes', 
        explain: 'Littéralement "chapeau de feuille" - car on se couvre la tête avec des feuilles quand il pleut fort.' 
    },
    { 
        expr: 'Lapli ka tombé, sé pa lapli, sé pis bèf', 
        hint: 'Quand il pleut vraiment très fort', 
        answer: 'Il pleut des vaches', 
        explain: 'Expression imagée pour dire qu\'il pleut énormément - encore plus fort que "chapo fey".' 
    },
    { 
        expr: 'Pòté chapò ba mwen', 
        hint: 'Expression de respect', 
        answer: 'Chapeau / Bravo', 
        explain: 'Littéralement "porter un chapeau pour moi" - signe de grand respect et admiration.' 
    },
    { 
        expr: 'Bat briyé', 
        hint: 'Être très intelligent', 
        answer: 'Avoir l\'esprit vif', 
        explain: 'Littéralement "battre brûlé" - avoir l\'esprit qui bat vite, être très éveillé.' 
    },
    { 
        expr: 'Chaché krab', 
        hint: 'Chercher des ennuis', 
        answer: 'Chercher la bagarre', 
        explain: 'Littéralement "chercher des crabes" - aller chercher quelque chose de difficile et potentiellement dangereux.' 
    },
    { 
        expr: 'Manjé fwomaj', 
        hint: 'Être embarrassé', 
        answer: 'Être gêné', 
        explain: 'Manger du fromage = sentiment de gêne, expression de malaise.' 
    },
    { 
        expr: 'Fè do won', 
        hint: 'Faire la tête', 
        answer: 'Bouder', 
        explain: 'Littéralement "faire le dos rond" comme un chat fâché.' 
    },
    { 
        expr: 'Kò a kò', 
        hint: 'Face à face', 
        answer: 'En tête-à-tête', 
        explain: 'Littéralement "corps à corps" - être ensemble en privé.' 
    },
    { 
        expr: 'Bay kou ba', 
        hint: 'Donner un coup de main', 
        answer: 'Aider', 
        explain: 'Littéralement "donner un coup bas" mais signifie aider, donner un coup de main.' 
    },
    { 
        expr: 'Koupé tèt', 
        hint: 'Prendre une décision rapide', 
        answer: 'Trancher', 
        explain: 'Littéralement "couper la tête" - prendre une décision claire et rapide.' 
    },
    { 
        expr: 'Fè yich', 
        hint: 'Faire des caprices', 
        answer: 'Faire des manières', 
        explain: 'Expression pour quelqu\'un qui fait le difficile ou des histoires.' 
    },
    { 
        expr: 'Mété dlo an bouch', 
        hint: 'Faire saliver', 
        answer: 'Mettre l\'eau à la bouche', 
        explain: 'Quand quelque chose a l\'air délicieux.' 
    },
    { 
        expr: 'Pwan van', 
        hint: 'Prendre la fuite', 
        answer: 'S\'enfuir rapidement', 
        explain: 'Littéralement "prendre le vent" - partir très vite.' 
    },
    { 
        expr: 'Tchenbé rèd', 
        hint: 'Tenir bon', 
        answer: 'Résister, persévérer', 
        explain: 'Littéralement "tenir raide" - ne pas lâcher, continuer malgré les difficultés.' 
    },
    { 
        expr: 'Bay lang', 
        hint: 'Raconter des ragots', 
        answer: 'Bavarder, médire', 
        explain: 'Littéralement "donner la langue" - parler des autres, faire des commérages.' 
    },
    { 
        expr: 'Fè kongo', 
        hint: 'Faire semblant', 
        answer: 'Faire l\'innocent', 
        explain: 'Faire comme si on ne sait rien, jouer la comédie.' 
    },
    { 
        expr: 'Pran kou divan', 
        hint: 'Être surpris', 
        answer: 'Être choqué', 
        explain: 'Recevoir un choc, être pris de court.' 
    },
    { 
        expr: 'Pété fèy', 
        hint: 'Partir rapidement', 
        answer: 'Déguerpir', 
        explain: 'Littéralement "péter les feuilles" - s\'en aller très vite.' 
    },
    { 
        expr: 'Fè zepòl', 
        hint: 'Ignorer volontairement', 
        answer: 'Hausser les épaules', 
        explain: 'Montrer son indifférence ou son désintérêt.' 
    },
    { 
        expr: 'Mété tèt ansanm', 
        hint: 'Travailler ensemble', 
        answer: 'Collaborer', 
        explain: 'Littéralement "mettre les têtes ensemble" - réfléchir ensemble pour trouver une solution.' 
    }
];

// ========================================
// 15+ EXERCICES VARIÉS
// ========================================
const exercises = [
    {
        type: 'fill',
        question: 'Complétez avec la bonne particule : Man ___ manjé pen (Je mange du pain)',
        options: ['ka', 'té', 'kay'],
        correct: 0
    },
    {
        type: 'fill',
        question: 'Complétez : Man ___ alé (Je suis allé)',
        options: ['ka', 'té', 'kay'],
        correct: 1
    },
    {
        type: 'fill',
        question: 'Complétez : Man ___ alé dèmen (J\'irai demain)',
        options: ['ka', 'té', 'kay'],
        correct: 2
    },
    {
        type: 'fill',
        question: 'Comment dit-on "les enfants" ?',
        options: ['timoun', 'sé timoun', 'timoun-la'],
        correct: 1
    },
    {
        type: 'fill',
        question: 'Quel pronom pour "Je" ?',
        options: ['Ou', 'Man', 'I', 'Nou'],
        correct: 1
    },
    {
        type: 'fill',
        question: 'Comment dire "Je ne sais pas" ?',
        options: ['Man sav', 'Man pa sav', 'Man té sav', 'Man kay sav'],
        correct: 1
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "Je cherche un restaurant"',
        words: ['Man', 'ka', 'chèché', 'an', 'restoran'],
        correct: 'Man ka chèché an restoran'
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "Les enfants jouent"',
        words: ['Sé', 'timoun', 'ka', 'jwé'],
        correct: 'Sé timoun ka jwé'
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "Où vas-tu ?"',
        words: ['Koté', 'ou', 'ka', 'alé'],
        correct: 'Koté ou ka alé'
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "Je t\'aime beaucoup"',
        words: ['Mwen', 'enmen', 'w', 'anlo'],
        correct: 'Mwen enmen w anlo'
    },
    {
        type: 'fill',
        question: 'Quelle particule pour le futur ?',
        options: ['ka', 'té', 'kay', 'pa'],
        correct: 2
    },
    {
        type: 'fill',
        question: 'Comment dire "une belle maison" ?',
        options: ['an bèl kay', 'an kay bèl', 'bèl an kay', 'kay an bèl'],
        correct: 1
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "J\'ai très faim"',
        words: ['Mwen', 'fen', 'anlo'],
        correct: 'Mwen fen anlo'
    },
    {
        type: 'fill',
        question: 'Comment dire "Merci beaucoup" ?',
        options: ['Mèsi', 'Mèsi anlo', 'Anlo mèsi', 'Mèsi bien'],
        correct: 1
    },
    {
        type: 'order',
        question: 'Remettez les mots dans l\'ordre : "Il fait beau aujourd\'hui"',
        words: ['I', 'fè', 'bèl', 'tan', 'jòdi'],
        correct: 'I fè bèl tan jòdi'
    }
];

// ========================================
// NOTE IMPORTANTE SUR LES SAISONS AUX ANTILLES
// ========================================
// Aux Antilles (Martinique et Guadeloupe), il y a DEUX SAISONS, pas quatre :
// 
// 1. KAREME (Carême) = Saison sèche (environ de décembre à mai)
//    - Moins de pluie, températures agréables
//    - Appelée aussi "la saison fraîche" bien qu'il fasse toujours chaud
//
// 2. HIVERNAGE (Hivernaj en créole) = Saison des pluies (environ de juin à novembre)
//    - Période des pluies tropicales, orages fréquents
//    - Saison des cyclones (août-octobre = période la plus à risque)
//    - Plus humide et plus chaud
//
// Traductions créoles :
// - Saison sèche = Karèm
// - Saison des pluies = Hivernaj / Lenivé
// - Cyclone = Siklon
//
// Note : La Guyane a un climat différent avec 4 saisons alternant sec/pluie

// Ajoutons ces mots au dictionnaire pour qu'ils soient reconnus par le traducteur
dictionary.push(
    { fr: 'Saison sèche', cr: 'Karèm', cat: 'Météo' },
    { fr: 'Carême', cr: 'Karèm', cat: 'Météo' },
    { fr: 'Saison des pluies', cr: 'Hivernaj', cat: 'Météo' },
    { fr: 'Hivernage', cr: 'Hivernaj', cat: 'Météo' }
);


